# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

#Create a cron schedule to run the script every 15 minutes
#RUN echo "*/15 * * * * /usr/local/bin/python /app/stockprice.py >> /var/log/cron.log 2>&1" > /etc/crontabs/root

# Run the cron daemon in the foreground
CMD ["python", "stockprice.py"]